### ISSUE TITLE
google_fit: Error on device update!

### ISSUE THREAD

**Issue by advokatb** [vmanuel/hacs-google-fit#11]
Hi.
I've got 
```log
2021-05-09 13:42:52 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
  File "d:\program\python\python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 407, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "d:\program\python\python38\lib\site-packages\homeassistant\helpers\entity.py", line 516, in async_device_update
    await task
  File "d:\program\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\program\python\python38\lib\site-packages\homeassistant\util\__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "d:\program\python\python38\lib\site-packages\homeassistant\util\__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "d:\User\.homeassistant\custom_components\google_fit\sensor.py", line 309, in update
    weight_datasources = self._get_datasources('com.google.weight')
  File "d:\User\.homeassistant\custom_components\google_fit\sensor.py", line 276, in _get_datasources
    data = datasources_request.execute()
  File "d:\User\.homeassistant\deps\Python38\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "d:\User\.homeassistant\deps\Python38\site-packages\googleapiclient\http.py", line 835, in execute
    resp, content = _retry_request(
  File "d:\User\.homeassistant\deps\Python38\site-packages\googleapiclient\http.py", line 163, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "d:\User\.homeassistant\deps\Python38\site-packages\oauth2client\transport.py", line 186, in new_request
    credentials._refresh(orig_request_method)
  File "d:\User\.homeassistant\deps\Python38\site-packages\oauth2client\client.py", line 756, in _refresh
    self._do_refresh_request(http)
  File "d:\User\.homeassistant\deps\Python38\site-packages\oauth2client\client.py", line 812, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Bad Request
```

What am I doing wrong?

I have this integration enabled and configured:

```yaml
- platform: google_fit
  name: Google Fit
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret
  scan_interval: 300
```

**Comment by mshuflin** [comment]
I have been getting the same since upgrading to 2021.5

Logger: homeassistant.components.sensor
Source: custom_components/google_fit/sensor.py:292
Integration: Sensor (documentation, issues)
First occurred: 2:40:44 PM (3 occurrences)
Last logged: 2:40:45 PM

google_fit: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 407, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 516, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/google_fit/sensor.py", line 397, in update
    weight_datasources = self._get_datasources('com.google.weight')
  File "/config/custom_components/google_fit/sensor.py", line 292, in _get_datasources
    data = datasources_request.execute()
  File "/usr/local/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 835, in execute
    resp, content = _retry_request(
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 163, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/oauth2client/transport.py", line 186, in new_request
    credentials._refresh(orig_request_method)
  File "/usr/local/lib/python3.8/site-packages/oauth2client/client.py", line 756, in _refresh
    self._do_refresh_request(http)
  File "/usr/local/lib/python3.8/site-packages/oauth2client/client.py", line 812, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Bad Request

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
