### ISSUE TITLE
Cannot authenticate - AttributeError: 'NoneType' object has no attribute 'users'

### ISSUE THREAD

**Issue by LordJABA** [vmanuel/hacs-google-fit#21]
I installed the integration via HACS 
After rebooting hass im getting notification:

Google Fit Setup

```
Error: Invalid response 400. Error: invalid_scope
You will need to restart hass after fixing.
```
But never any login code message as I get with google calendar for example
No `.token` files are created in config folder.

And in logs I have this error message:
```

Logger: homeassistant.components.sensor
Source: custom_components/google_fit/sensor.py:293
Integration: Sensor (documentation, issues)
First occurred: 11:04:27 (1 occurrences)
Last logged: 11:04:27

google_fit: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 735, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/google_fit/sensor.py", line 460, in update
    height_datasources = self._get_datasources('com.google.height')
  File "/config/custom_components/google_fit/sensor.py", line 293, in _get_datasources
    datasources_request = self._client.users().dataSources().list(
AttributeError: 'NoneType' object has no attribute 'users'
```
Tried removing pycache, reinstalling, creating the token file by hand based on OAuth Playground always the same error and no .token file

**Comment by posreg** [comment]
did you find any solution ?

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
