### ISSUE TITLE
Not loading custom component

### ISSUE THREAD

**Issue by geyles** [vmanuel/hacs-google-fit#7]
2020-05-04 22:20:56 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.google_fit​. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 393, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.google_fit\u200b'

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
